"""Add libelle to MyWittiMouvement

Revision ID: 4c4b27ed67c9
Revises: b188b6b70509
Create Date: 2025-11-01 13:54:15.850769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c4b27ed67c9'
down_revision = 'b188b6b70509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_requests')
    op.drop_table('survey_responses')
    op.drop_table('surveys')
    op.drop_table('survey_options')
    with op.batch_alter_table('mywitti_mouvement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('libelle', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mywitti_mouvement', schema=None) as batch_op:
        batch_op.drop_column('libelle')

    op.create_table('survey_options',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('option_text', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('option_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name='survey_options_survey_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='survey_options_pkey')
    )
    op.create_table('surveys',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('surveys_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='surveys_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('option_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['mywitti_client.id'], name='survey_responses_customer_id_fkey'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], name='survey_responses_survey_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['mywitti_users.id'], name='survey_responses_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='survey_responses_pkey')
    )
    op.create_table('support_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mywitti_users.id'], name='support_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='support_requests_pkey')
    )
    # ### end Alembic commands ###
